//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Dzaba.HomeSecurity.Devices.Contracts
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// A network device (MAC address) seen on a tenant's home network. Identity is (tenant, macAddress). Distinct from the agent's own auth credential, which lives in Org.Service.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Device
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("macAddress")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$")]
        public string MacAddress { get; set; }

        /// <summary>
        /// Optional, user-assigned
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("name")]
        [System.ComponentModel.DataAnnotations.StringLength(200)]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<Device_status>))]
        public Device_status Status { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("firstSeenAt")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset FirstSeenAt { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("lastSeenAt")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset LastSeenAt { get; set; }

        /// <summary>
        /// The router whose agent last reported this device; traceability only, not part of its identity
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("lastSeenViaRouterId")]
        public System.Guid? LastSeenViaRouterId { get; set; }

    }
}