//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Dzaba.HomeSecurity.Devices.Contracts
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// Unknown until a user acknowledges the device ('this is mine'), then Known. See docs/architecture/06-notifications.md.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum Device_status
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"Unknown")]
        [System.Runtime.Serialization.EnumMember(Value = @"Unknown")]
        Unknown = 0,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"Known")]
        [System.Runtime.Serialization.EnumMember(Value = @"Known")]
        Known = 1,


    }
}