//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Dzaba.HomeSecurity.Devices.Contracts
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// Notification only, not event-carried state transfer: a device was renamed or acknowledged - a consumer should call Devices.Service's API for current data, never reconstruct state from this event alone. No consumer exists yet - published as a low-cost hedge for future integrations.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class DeviceChangedMessage
    {

        [System.Text.Json.Serialization.JsonPropertyName("tenantId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid TenantId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("deviceId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid DeviceId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("macAddress")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string MacAddress { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<Device_status>))]
        public Device_status Status { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("changedAt")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset ChangedAt { get; set; }

    }
}