//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Dzaba.HomeSecurity.Devices.Contracts
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// A home router's metadata. Never carries the secret, encrypted or not: it is write-only.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Router
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(200, MinimumLength = 1)]
        public string Name { get; set; }

        /// <summary>
        /// Host name or IP address on the home network
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("host")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(255, MinimumLength = 1)]
        public string Host { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("protocol")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<Router_protocol>))]
        public Router_protocol Protocol { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("authMode")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<Router_auth_mode>))]
        public Router_auth_mode? AuthMode { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("username")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(200)]
        public string Username { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("updatedAt")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset UpdatedAt { get; set; }

    }
}