//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Dzaba.HomeSecurity.Devices.Contracts
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// How an agent reaches the router it is paired with, including the decrypted secret. Only ever returned to that agent, over HTTPS, to the device-token-authenticated router-config endpoint; never logged.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class RouterConfig
    {

        [System.Text.Json.Serialization.JsonPropertyName("routerId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid RouterId { get; set; }

        /// <summary>
        /// Host name or IP address on the home network
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("host")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(255, MinimumLength = 1)]
        public string Host { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("protocol")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<Router_protocol>))]
        public Router_protocol Protocol { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("authMode")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<Router_auth_mode>))]
        public Router_auth_mode? AuthMode { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("username")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(200)]
        public string Username { get; set; }

        /// <summary>
        /// The router password or SNMP community string, in plaintext
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("secret")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Secret { get; set; }

        /// <summary>
        /// When the router's settings last changed, so the agent knows when to refresh
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("updatedAt")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset UpdatedAt { get; set; }

    }
}