//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Dzaba.HomeSecurity.Devices.Contracts
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// How the agent reads a router's connected-device list. See docs/architecture/15-router-credentials.md.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum Router_protocol
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"WebScrape")]
        [System.Runtime.Serialization.EnumMember(Value = @"WebScrape")]
        WebScrape = 0,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"SNMP")]
        [System.Runtime.Serialization.EnumMember(Value = @"SNMP")]
        SNMP = 1,


    }
}