//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Dzaba.HomeSecurity.Devices.Contracts
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// Notification only, not event-carried state transfer: a router was created, updated or deleted - a consumer should call Devices.Service's API for current data, never reconstruct state from this event alone. No consumer exists yet - published as a low-cost hedge for future integrations.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class RouterChangedMessage
    {

        [System.Text.Json.Serialization.JsonPropertyName("tenantId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid TenantId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("routerId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid RouterId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("action")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<RouterChangedMessageAction>))]
        public RouterChangedMessageAction Action { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("changedAt")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset ChangedAt { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum RouterChangedMessageAction
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"Created")]
        [System.Runtime.Serialization.EnumMember(Value = @"Created")]
        Created = 0,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"Updated")]
        [System.Runtime.Serialization.EnumMember(Value = @"Updated")]
        Updated = 1,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"Deleted")]
        [System.Runtime.Serialization.EnumMember(Value = @"Deleted")]
        Deleted = 2,


    }
}