//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Dzaba.HomeSecurity.Devices.Contracts
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// How the agent presents a WebScrape router's credentials - only meaningful for the WebScrape protocol. See docs/architecture/15-router-credentials.md.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum Router_auth_mode
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"HttpBasic")]
        [System.Runtime.Serialization.EnumMember(Value = @"HttpBasic")]
        HttpBasic = 0,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"HttpDigest")]
        [System.Runtime.Serialization.EnumMember(Value = @"HttpDigest")]
        HttpDigest = 1,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"FormLogin")]
        [System.Runtime.Serialization.EnumMember(Value = @"FormLogin")]
        FormLogin = 2,


    }
}