//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Dzaba.HomeSecurity.Audit.Contracts
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// The immutable record of one security-relevant action (who did what, to which tenant's data, and when), published under an audit.&lt;action&gt; routing key. Not a notification: unlike the *.changed events it is never used to re-check current state, and Audit.Service stores it verbatim. See docs/architecture/16-auditing-and-compliance.md. metadata is action-specific and must never carry a secret, a JWT, a plaintext credential or a raw log payload.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class AuditEventMessage
    {

        /// <summary>
        /// Idempotency key: Audit.Service drops a second event with the same id.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("eventId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid EventId { get; set; }

        /// <summary>
        /// Set by the producing service when the action happened.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("occurredAt")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset OccurredAt { get; set; }

        /// <summary>
        /// Null for pre-tenant events such as a login.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("tenantId")]
        public System.Guid? TenantId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("actor")]
        [System.ComponentModel.DataAnnotations.Required]
        public Actor Actor { get; set; } = new Actor();

        /// <summary>
        /// Dotted lower-case action name, e.g. role.assigned or router.credential.fetched. The routing key is audit.&lt;action&gt;.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("action")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(100)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$")]
        public string Action { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("target")]
        [System.ComponentModel.DataAnnotations.Required]
        public Target Target { get; set; } = new Target();

        /// <summary>
        /// Action-specific detail (identifiers and before/after of what changed); never a secret value.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("metadata")]
        [System.ComponentModel.DataAnnotations.Required]
        public object Metadata { get; set; } = new object();

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Actor
    {

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<ActorType>))]
        public ActorType Type { get; set; }

        /// <summary>
        /// Keycloak subject for a User, the agent credential id for a Device.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(200, MinimumLength = 1)]
        public string Id { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Target
    {

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(100, MinimumLength = 1)]
        public string Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(200, MinimumLength = 1)]
        public string Id { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum ActorType
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"User")]
        [System.Runtime.Serialization.EnumMember(Value = @"User")]
        User = 0,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"Device")]
        [System.Runtime.Serialization.EnumMember(Value = @"Device")]
        Device = 1,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"System")]
        [System.Runtime.Serialization.EnumMember(Value = @"System")]
        System = 2,


    }
}