<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <JsonSchema Include="..\..\..\contracts\json\audit_event_message.json" Link="audit_event_message.json" OutputFile="AuditEventMessage.cs" ClassName="AuditEventMessage" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NSwag.MSBuild">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <Import Project="..\..\..\..\build\JsonSchema.targets" />

</Project>
