//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Dzaba.HomeSecurity.Authorization.OrgApi
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// The calling user's effective permissions in one organization. Membership is implied by the response itself: a non-member never gets a body, the tenant-resolution middleware answers 404 first, so 200 always means 'member'. Consumed by services that don't own Membership/UserRole/RolePermission directly (see docs/decisions/0016-devices-service-owns-its-own-database.md).
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class AccessContextResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("permissionKeys")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<string> PermissionKeys { get; set; } = new System.Collections.ObjectModel.Collection<string>();

    }
}