<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <JsonSchema Include="..\..\..\contracts\json\organization.json" Link="organization.json" OutputFile="Organization.cs" ClassName="Organization" />
    <JsonSchema Include="..\..\..\contracts\json\permission.json" Link="permission.json" OutputFile="Permission.cs" ClassName="Permission"  />
    <JsonSchema Include="..\..\..\contracts\json\role.json" Link="role.json" OutputFile="Role.cs" ClassName="Role" />
    <JsonSchema Include="..\..\..\contracts\json\create_organization.json" Link="create_organization.json" OutputFile="CreateOrganization.cs" ClassName="CreateOrganization" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
    <PackageReference Include="NSwag.MSBuild">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <Import Project="..\..\..\..\build\JsonSchema.targets" />
</Project>
