// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contracts

import "encoding/json"
import "fmt"
import "reflect"
import "regexp"
import "time"
import "unicode/utf8"

// The log lines pertaining to one network device, observed in a single upload.
type DeviceLogs struct {
	// Device corresponds to the JSON schema field "device".
	Device NetworkDevice `json:"device"`

	// Events corresponds to the JSON schema field "events".
	Events []LogEntry `json:"events"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DeviceLogs) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["device"]; raw != nil && !ok {
		return fmt.Errorf("field device in DeviceLogs: required")
	}
	if _, ok := raw["events"]; raw != nil && !ok {
		return fmt.Errorf("field events in DeviceLogs: required")
	}
	type Plain DeviceLogs
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Events != nil && len(plain.Events) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "events", 1)
	}
	if len(plain.Events) > 1000 {
		return fmt.Errorf("field %s length: must be <= %d", "events", 1000)
	}
	*j = DeviceLogs(plain)
	return nil
}

type LogBatchMessage struct {
	// The agent credential's own id, not a network device.
	DeviceId string `json:"deviceId"`

	// Devices corresponds to the JSON schema field "devices".
	Devices []DeviceLogs `json:"devices"`

	// Idempotency key for the consuming worker's Redis SETNX check.
	MessageId string `json:"messageId"`

	// TenantId corresponds to the JSON schema field "tenantId".
	TenantId string `json:"tenantId"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LogBatchMessage) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["deviceId"]; raw != nil && !ok {
		return fmt.Errorf("field deviceId in LogBatchMessage: required")
	}
	if _, ok := raw["devices"]; raw != nil && !ok {
		return fmt.Errorf("field devices in LogBatchMessage: required")
	}
	if _, ok := raw["messageId"]; raw != nil && !ok {
		return fmt.Errorf("field messageId in LogBatchMessage: required")
	}
	if _, ok := raw["tenantId"]; raw != nil && !ok {
		return fmt.Errorf("field tenantId in LogBatchMessage: required")
	}
	type Plain LogBatchMessage
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Devices != nil && len(plain.Devices) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "devices", 1)
	}
	if len(plain.Devices) > 1000 {
		return fmt.Errorf("field %s length: must be <= %d", "devices", 1000)
	}
	*j = LogBatchMessage(plain)
	return nil
}

type LogEntry struct {
	// Unique event identifier, used downstream as an idempotency key.
	EventId string `json:"eventId"`

	// Level corresponds to the JSON schema field "level".
	Level LogEntryLevel `json:"level"`

	// Message corresponds to the JSON schema field "message".
	Message string `json:"message"`

	// When the router reported this log line, as recorded by the agent.
	Timestamp time.Time `json:"timestamp"`
}

type LogEntryLevel string

const LogEntryLevelCritical LogEntryLevel = "critical"
const LogEntryLevelDebug LogEntryLevel = "debug"
const LogEntryLevelError LogEntryLevel = "error"
const LogEntryLevelInfo LogEntryLevel = "info"
const LogEntryLevelWarning LogEntryLevel = "warning"

var enumValues_LogEntryLevel = []interface{}{
	"debug",
	"info",
	"warning",
	"error",
	"critical",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LogEntryLevel) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_LogEntryLevel {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_LogEntryLevel, v)
	}
	*j = LogEntryLevel(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LogEntry) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["eventId"]; raw != nil && !ok {
		return fmt.Errorf("field eventId in LogEntry: required")
	}
	if _, ok := raw["level"]; raw != nil && !ok {
		return fmt.Errorf("field level in LogEntry: required")
	}
	if _, ok := raw["message"]; raw != nil && !ok {
		return fmt.Errorf("field message in LogEntry: required")
	}
	if _, ok := raw["timestamp"]; raw != nil && !ok {
		return fmt.Errorf("field timestamp in LogEntry: required")
	}
	type Plain LogEntry
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Message)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "message", 1)
	}
	if utf8.RuneCountInString(string(plain.Message)) > 4096 {
		return fmt.Errorf("field %s length: must be <= %d", "message", 4096)
	}
	*j = LogEntry(plain)
	return nil
}

// A device observed on the tenant's LAN - distinct from the agent credential
// ('Device' in the Data project) that authenticates the upload itself.
type NetworkDevice struct {
	// Hostname corresponds to the JSON schema field "hostname".
	Hostname *string `json:"hostname,omitempty,omitzero"`

	// IpAddress corresponds to the JSON schema field "ipAddress".
	IpAddress *string `json:"ipAddress,omitempty,omitzero"`

	// MacAddress corresponds to the JSON schema field "macAddress".
	MacAddress string `json:"macAddress"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NetworkDevice) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["macAddress"]; raw != nil && !ok {
		return fmt.Errorf("field macAddress in NetworkDevice: required")
	}
	type Plain NetworkDevice
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Hostname != nil && utf8.RuneCountInString(string(*plain.Hostname)) > 255 {
		return fmt.Errorf("field %s length: must be <= %d", "hostname", 255)
	}
	if plain.IpAddress != nil && utf8.RuneCountInString(string(*plain.IpAddress)) > 45 {
		return fmt.Errorf("field %s length: must be <= %d", "ipAddress", 45)
	}
	if matched, _ := regexp.MatchString(`^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$`, string(plain.MacAddress)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "MacAddress", `^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$`)
	}
	*j = NetworkDevice(plain)
	return nil
}
