<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <PermissionSchema>$(MSBuildProjectDirectory)\..\..\..\contracts\json\permission.json</PermissionSchema>
    <PermissionOutput>$(MSBuildProjectDirectory)\Permission.cs</PermissionOutput>
    <OrganizationSchema>$(MSBuildProjectDirectory)\..\..\..\contracts\json\organization.json</OrganizationSchema>
    <OrganizationOutput>$(MSBuildProjectDirectory)\Organization.cs</OrganizationOutput>
    <RoleSchema>$(MSBuildProjectDirectory)\..\..\..\contracts\json\role.json</RoleSchema>
    <RoleOutput>$(MSBuildProjectDirectory)\Role.cs</RoleOutput>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\..\contracts\json\organization.json" Link="organization.json" />
    <None Include="..\..\..\contracts\json\permission.json" Link="permission.json" />
    <None Include="..\..\..\contracts\json\role.json" Link="role.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
    <PackageReference Include="NSwag.MSBuild">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <Target Name="GeneratePermissionContracts" BeforeTargets="CoreCompile" Inputs="$(PermissionSchema)" Outputs="$(PermissionOutput)">
    <Exec Command="$(NSwagExe) jsonschema2csclient /input:$(PermissionSchema) /output:$(PermissionOutput) /namespace:$(RootNameSpace) /name:Permission /jsonlibrary:SystemTextJson" ConsoleToMSBuild="true">
      <Output TaskParameter="ConsoleOutput" PropertyName="OutputOfExec" />
    </Exec>
  </Target>

  <Target Name="GenerateOrganizationContracts" BeforeTargets="CoreCompile" Inputs="$(OrganizationSchema)" Outputs="$(OrganizationOutput)">
    <Exec Command="$(NSwagExe) jsonschema2csclient /input:$(OrganizationSchema) /output:$(OrganizationOutput) /namespace:$(RootNameSpace) /name:Organization /jsonlibrary:SystemTextJson" ConsoleToMSBuild="true">
      <Output TaskParameter="ConsoleOutput" PropertyName="OutputOfExec" />
    </Exec>
  </Target>

  <Target Name="GenerateRoleContracts" BeforeTargets="CoreCompile" Inputs="$(RoleSchema)" Outputs="$(RoleOutput)">
    <Exec Command="$(NSwagExe) jsonschema2csclient /input:$(RoleSchema) /output:$(RoleOutput) /namespace:$(RootNameSpace) /name:Role /jsonlibrary:SystemTextJson" ConsoleToMSBuild="true">
      <Output TaskParameter="ConsoleOutput" PropertyName="OutputOfExec" />
    </Exec>
  </Target>

  <Target Name="ForceReGenerationOnRebuild" AfterTargets="CoreClean">
    <Delete Files="$(OrganizationOutput)"></Delete>
    <Delete Files="$(PermissionOutput)"></Delete>
    <Delete Files="$(RoleOutput)"></Delete>
  </Target>
</Project>
