//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Dzaba.HomeSecurity.Org.Contracts
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// Notification only, not event-carried state transfer: something about this (tenant, user) pair's access changed, a consumer should re-check via the access-context endpoint or the shared permission cache - never reconstruct state from this event alone. No consumer exists yet - published as a low-cost hedge for future integrations.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class AccessChangedMessage
    {

        [System.Text.Json.Serialization.JsonPropertyName("tenantId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid TenantId { get; set; }

        /// <summary>
        /// Keycloak subject (sub claim) whose access changed
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("userId")]
        [System.ComponentModel.DataAnnotations.Required]
        public string UserId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("changedAt")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset ChangedAt { get; set; }

    }
}