//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Dzaba.HomeSecurity.Org.Contracts
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class AssignUserRole
    {

        /// <summary>
        /// Keycloak subject (sub claim) of the user to assign the role to
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("userId")]
        [System.ComponentModel.DataAnnotations.Required]
        public string UserId { get; set; }

        /// <summary>
        /// The role to assign
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("roleId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid RoleId { get; set; }

    }
}