//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Dzaba.HomeSecurity.Org.Contracts
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Membership
    {

        /// <summary>
        /// The organization this membership belongs to
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("organizationId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid OrganizationId { get; set; }

        /// <summary>
        /// Keycloak subject (sub claim) of the member
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("userId")]
        [System.ComponentModel.DataAnnotations.Required]
        public string UserId { get; set; }

    }
}