syntax = "proto3";

package dzaba.home.security.logs.v1;

option csharp_namespace = "Dzaba.HomeSecurity.LogsIngestion.Contracts";

message LogEvent {
  string event_id = 1;
  string home_id = 2;
  string device_id = 3;
  LogLevel level = 4;
  string message = 5;
}

enum LogLevel {
  LOG_LEVEL_UNSPECIFIED = 0;
  LOG_LEVEL_DEBUG = 1;
  LOG_LEVEL_INFO = 2;
  LOG_LEVEL_WARNING = 3;
  LOG_LEVEL_ERROR = 4;
  LOG_LEVEL_CRITICAL = 5;
}

message IngestLogsRequest {
  repeated LogEvent events = 1;
}

message IngestLogsResponse {
}
