//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Dzaba.HomeSecurity.DomainEvents
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// One thing a service did to a tenant's data, access or credentials (a membership was added, a role was assigned, a router credential was fetched), published by the service that did it under a routing key equal to action. Any number of services may subscribe; Audit.Service is one of them and stores each event verbatim as the record of who did what, to which tenant's data, and when. Not event-carried state transfer: a subscriber that needs current state calls the owning service's API. metadata carries the action-specific extended data and must never carry a secret, a JWT, a plaintext credential or a raw log payload. See docs/architecture/16-auditing-and-compliance.md.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class DomainEventMessage
    {

        /// <summary>
        /// Idempotency key: a subscriber drops a second event with the same id (Audit.Service does so by a unique index).
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("eventId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid EventId { get; set; }

        /// <summary>
        /// Set by the publishing service when the action happened.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("occurredAt")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset OccurredAt { get; set; }

        /// <summary>
        /// Null for pre-tenant events such as a login.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("tenantId")]
        public System.Guid? TenantId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("actor")]
        [System.ComponentModel.DataAnnotations.Required]
        public Actor Actor { get; set; } = new Actor();

        /// <summary>
        /// Dotted lower-case event name, e.g. membership.added or router.credential.fetched. It is also the routing key the event is published under.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("action")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(100)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$")]
        public string Action { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("target")]
        [System.ComponentModel.DataAnnotations.Required]
        public Target Target { get; set; } = new Target();

        /// <summary>
        /// Action-specific extended data (identifiers and the before/after of what changed); never a secret value.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("metadata")]
        [System.ComponentModel.DataAnnotations.Required]
        public object Metadata { get; set; } = new object();

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Actor
    {

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<ActorType>))]
        public ActorType Type { get; set; }

        /// <summary>
        /// Keycloak subject for a User, the agent credential id for a Device.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(200, MinimumLength = 1)]
        public string Id { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Target
    {

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(100, MinimumLength = 1)]
        public string Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(200, MinimumLength = 1)]
        public string Id { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum ActorType
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"User")]
        [System.Runtime.Serialization.EnumMember(Value = @"User")]
        User = 0,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"Device")]
        [System.Runtime.Serialization.EnumMember(Value = @"Device")]
        Device = 1,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"System")]
        [System.Runtime.Serialization.EnumMember(Value = @"System")]
        System = 2,


    }
}