//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Dzaba.HomeSecurity.LogsIngestion.Contracts
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// The log lines pertaining to one network device, observed in a single upload.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Device_logs
    {

        [System.Text.Json.Serialization.JsonPropertyName("device")]
        [System.ComponentModel.DataAnnotations.Required]
        public Network_device Device { get; set; } = new Network_device();

        [System.Text.Json.Serialization.JsonPropertyName("events")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.MinLength(1)]
        [System.ComponentModel.DataAnnotations.MaxLength(1000)]
        public System.Collections.Generic.ICollection<Log_entry> Events { get; set; } = new System.Collections.ObjectModel.Collection<Log_entry>();

    }
}