//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Dzaba.HomeSecurity.LogsIngestion.Contracts
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class IngestLogsRequest
    {

        /// <summary>
        /// One entry per network device the agent observed since its last upload, each carrying the log lines that pertain to it.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("devices")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.MinLength(1)]
        [System.ComponentModel.DataAnnotations.MaxLength(1000)]
        public System.Collections.Generic.ICollection<Device_logs> Devices { get; set; } = new System.Collections.ObjectModel.Collection<Device_logs>();

    }
}