//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Dzaba.HomeSecurity.LogsIngestion.Contracts
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Log_entry
    {

        /// <summary>
        /// Unique event identifier, used downstream as an idempotency key.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("eventId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid EventId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("level")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<Log_entryLevel>))]
        public Log_entryLevel Level { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("message")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(4096, MinimumLength = 1)]
        public string Message { get; set; }

        /// <summary>
        /// When the router reported this log line, as recorded by the agent.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("timestamp")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset Timestamp { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum Log_entryLevel
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"debug")]
        [System.Runtime.Serialization.EnumMember(Value = @"debug")]
        Debug = 0,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"info")]
        [System.Runtime.Serialization.EnumMember(Value = @"info")]
        Info = 1,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"warning")]
        [System.Runtime.Serialization.EnumMember(Value = @"warning")]
        Warning = 2,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"error")]
        [System.Runtime.Serialization.EnumMember(Value = @"error")]
        Error = 3,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"critical")]
        [System.Runtime.Serialization.EnumMember(Value = @"critical")]
        Critical = 4,


    }
}