//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Dzaba.HomeSecurity.LogsIngestion.Contracts
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class LogBatchMessage
    {

        /// <summary>
        /// Idempotency key for the consuming worker's Redis SETNX check.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("messageId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid MessageId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("tenantId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid TenantId { get; set; }

        /// <summary>
        /// The agent credential's own id, not a network device.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("deviceId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid DeviceId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("devices")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.MinLength(1)]
        [System.ComponentModel.DataAnnotations.MaxLength(1000)]
        public System.Collections.Generic.ICollection<Device_logs> Devices { get; set; } = new System.Collections.ObjectModel.Collection<Device_logs>();

    }
}