//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Dzaba.HomeSecurity.LogsIngestion.Contracts
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// A device observed on the tenant's LAN - distinct from the agent credential ('Device' in the Data project) that authenticates the upload itself.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.6.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Network_device
    {

        [System.Text.Json.Serialization.JsonPropertyName("macAddress")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$")]
        public string MacAddress { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ipAddress")]
        [System.ComponentModel.DataAnnotations.StringLength(45)]
        public string IpAddress { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("hostname")]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public string Hostname { get; set; }

    }
}