#!/usr/bin/env pwsh
<#
Generates src/.env and src/config/keycloak/realm-export.json with fresh
random credentials for the local docker compose stack. Neither file is
committed to git - re-run this on every fresh clone/environment.
#>
[CmdletBinding()]
param(
    [switch]$Force,
    # Adds a throwaway public client ("dev-test-client", direct access
    # grants enabled) and a matching user ("dev-test-user") to the
    # generated realm-export.json only - never to the committed .template.
    # Lets you fetch a real bearer token locally via the OIDC password
    # grant (curl/Postman) without driving the full oauth2-proxy browser
    # flow. Not for anything beyond local manual testing.
    [switch]$DevTestUser
)

$ErrorActionPreference = 'Stop'

$envPath = Join-Path $PSScriptRoot '.env'
$realmTemplatePath = Join-Path $PSScriptRoot 'config/keycloak/realm-export.json.template'
$realmOutputPath = Join-Path $PSScriptRoot 'config/keycloak/realm-export.json'

if ((Test-Path $envPath) -and -not $Force) {
    Write-Host "src/.env already exists - skipping. Pass -Force to regenerate (see the docker compose down -v note in README.md first)."
    exit 0
}

function New-HexSecret {
    param([int]$ByteLength = 16)
    $bytes = [byte[]]::new($ByteLength)
    [System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
    return [System.Convert]::ToHexString($bytes).ToLowerInvariant()
}

$postgresKeycloakPassword = New-HexSecret
$postgresAppPassword = New-HexSecret
$keycloakAdminPassword = New-HexSecret
$rabbitmqPassword = New-HexSecret
$oauth2ProxyClientSecret = New-HexSecret
$oauth2ProxyCookieSecret = New-HexSecret
$grafanaAdminPassword = New-HexSecret
$logsDeviceTokensSigningKey = New-HexSecret -ByteLength 32
$devicesDeviceTokensSigningKey = New-HexSecret -ByteLength 32

$envContent = @"
# Generated by init.ps1 - local dev only, never commit this file.

POSTGRES_KEYCLOAK_DB=keycloak
POSTGRES_KEYCLOAK_USER=keycloak
POSTGRES_KEYCLOAK_PASSWORD=$postgresKeycloakPassword

POSTGRES_APP_DB=homesecurity
POSTGRES_APP_USER=homesecurity
POSTGRES_APP_PASSWORD=$postgresAppPassword

KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD=$keycloakAdminPassword

RABBITMQ_DEFAULT_USER=homesecurity
RABBITMQ_DEFAULT_PASS=$rabbitmqPassword

# Symmetric key the Logs Ingestion API validates device JWTs against - the
# not-yet-built device-token endpoint will sign with this same key once it
# exists. See docs/architecture/03-security-and-identity.md.
LOGS_DEVICE_TOKENS_SIGNING_KEY=$logsDeviceTokensSigningKey

# Same idea for the Devices API's agent router-config endpoint; a separate
# key from the Logs Ingestion one.
DEVICES_DEVICE_TOKENS_SIGNING_KEY=$devicesDeviceTokensSigningKey

OAUTH2_PROXY_CLIENT_SECRET=$oauth2ProxyClientSecret
OAUTH2_PROXY_COOKIE_SECRET=$oauth2ProxyCookieSecret

GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=$grafanaAdminPassword
"@

Set-Content -Path $envPath -Value $envContent -NoNewline

$realmTemplate = Get-Content -Path $realmTemplatePath -Raw
$realmContent = $realmTemplate.Replace('__OAUTH2_PROXY_CLIENT_SECRET__', $oauth2ProxyClientSecret)

if ($DevTestUser) {
    $realm = $realmContent | ConvertFrom-Json

    $realm.clients += [PSCustomObject]@{
        clientId                  = 'dev-test-client'
        enabled                   = $true
        protocol                  = 'openid-connect'
        publicClient              = $true
        standardFlowEnabled       = $false
        directAccessGrantsEnabled = $true
        defaultClientScopes       = @('email', 'profile', 'home-security-api-audience')
    }

    $realm | Add-Member -NotePropertyName 'users' -NotePropertyValue @(
        [PSCustomObject]@{
            username      = 'dev-test-user'
            enabled       = $true
            firstName     = 'Dev'
            lastName      = 'Test'
            email         = 'dev-test-user@example.local'
            emailVerified = $true
            credentials   = @(
                [PSCustomObject]@{
                    type      = 'password'
                    value     = 'dev-test-password'
                    temporary = $false
                }
            )
        }
    ) -Force

    $realmContent = $realm | ConvertTo-Json -Depth 10
}

Set-Content -Path $realmOutputPath -Value $realmContent -NoNewline

Write-Host "Wrote $envPath"
Write-Host "Wrote $realmOutputPath"
if ($DevTestUser) {
    Write-Host "Dev test login: username 'dev-test-user', password 'dev-test-password', client_id 'dev-test-client' (password grant, local testing only)"
}
Write-Host "Next: docker compose up -d"
