#!/usr/bin/env pwsh
<#
Generates src/.env and src/config/keycloak/realm-export.json with fresh
random credentials for the local docker compose stack. Neither file is
committed to git - re-run this on every fresh clone/environment.
#>
[CmdletBinding()]
param(
    [switch]$Force
)

$ErrorActionPreference = 'Stop'

$envPath = Join-Path $PSScriptRoot '.env'
$realmTemplatePath = Join-Path $PSScriptRoot 'config/keycloak/realm-export.json.template'
$realmOutputPath = Join-Path $PSScriptRoot 'config/keycloak/realm-export.json'

if ((Test-Path $envPath) -and -not $Force) {
    Write-Host "src/.env already exists - skipping. Pass -Force to regenerate (see the docker compose down -v note in README.md first)."
    exit 0
}

function New-HexSecret {
    param([int]$ByteLength = 16)
    $bytes = [byte[]]::new($ByteLength)
    [System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
    return [System.Convert]::ToHexString($bytes).ToLowerInvariant()
}

$postgresKeycloakPassword = New-HexSecret
$postgresAppPassword = New-HexSecret
$keycloakAdminPassword = New-HexSecret
$rabbitmqPassword = New-HexSecret
$oauth2ProxyClientSecret = New-HexSecret
$oauth2ProxyCookieSecret = New-HexSecret
$grafanaAdminPassword = New-HexSecret

$envContent = @"
# Generated by init.ps1 - local dev only, never commit this file.

POSTGRES_KEYCLOAK_DB=keycloak
POSTGRES_KEYCLOAK_USER=keycloak
POSTGRES_KEYCLOAK_PASSWORD=$postgresKeycloakPassword

POSTGRES_APP_DB=homesecurity
POSTGRES_APP_USER=homesecurity
POSTGRES_APP_PASSWORD=$postgresAppPassword

KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD=$keycloakAdminPassword

RABBITMQ_DEFAULT_USER=homesecurity
RABBITMQ_DEFAULT_PASS=$rabbitmqPassword

OAUTH2_PROXY_CLIENT_SECRET=$oauth2ProxyClientSecret
OAUTH2_PROXY_COOKIE_SECRET=$oauth2ProxyCookieSecret

GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=$grafanaAdminPassword
"@

Set-Content -Path $envPath -Value $envContent -NoNewline

$realmTemplate = Get-Content -Path $realmTemplatePath -Raw
$realmContent = $realmTemplate.Replace('__OAUTH2_PROXY_CLIENT_SECRET__', $oauth2ProxyClientSecret)
Set-Content -Path $realmOutputPath -Value $realmContent -NoNewline

Write-Host "Wrote $envPath"
Write-Host "Wrote $realmOutputPath"
Write-Host "Next: docker compose up -d"
