<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
		<LogsSchema>$(MSBuildProjectDirectory)\..\..\..\contracts\json\log_event.json</LogsSchema>
		<LogsOutput>$(MSBuildProjectDirectory)\LogsModel.cs</LogsOutput>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NSwag.MSBuild" Version="14.6.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

	<Target Name="GenerateLogContracts" BeforeTargets="CoreCompile" Inputs="$(LogsSchema)" Outputs="$(LogsOutput)">
		<Exec Command="$(NSwagExe) jsonschema2csclient /input:$(LogsSchema) /output:$(LogsOutput) /namespace:$(RootNameSpace) /name:IngestLogsRequest /jsonlibrary:SystemTextJson" ConsoleToMSBuild="true">
			<Output TaskParameter="ConsoleOutput" PropertyName="OutputOfExec" />
		</Exec>
	</Target>
	<Target Name="ForceReGenerationOnRebuild" AfterTargets="CoreClean">
		<Delete Files="$(LogsOutput)"></Delete>
	</Target>
</Project>
