//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Dzaba.HomeSecurity.LogsIngestion.Contracts
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class IngestLogsRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("events")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.MinLength(1)]
        [System.ComponentModel.DataAnnotations.MaxLength(1000)]
        public System.Collections.Generic.ICollection<Events> Events { get; set; } = new System.Collections.ObjectModel.Collection<Events>();

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Events
    {

        /// <summary>
        /// Unique event identifier for idempotency
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("eventId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid EventId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("homeId")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(128, MinimumLength = 1)]
        public string HomeId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("deviceId")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(128, MinimumLength = 1)]
        public string DeviceId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("level")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<EventsLevel>))]
        public EventsLevel Level { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("message")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(4096, MinimumLength = 1)]
        public string Message { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum EventsLevel
    {

        [System.Runtime.Serialization.EnumMember(Value = @"debug")]
        Debug = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"info")]
        Info = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"warning")]
        Warning = 2,


        [System.Runtime.Serialization.EnumMember(Value = @"error")]
        Error = 3,


        [System.Runtime.Serialization.EnumMember(Value = @"critical")]
        Critical = 4,


    }
}